name: Semi-Auto Build & Release

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: write # ✅ allow pushing tags & creating releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important so tags are fetched

      - name: Get plugin version
        id: get_version
        run: |
          VERSION=$(grep -i "Version:" popular-search.php | sed -E 's/.*Version:[[:space:]]*([0-9.]+).*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Create tag
        if: env.exists == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Zip Plugin
        run: |
          mkdir -p dist
          zip -r dist/popular-search.zip . -x "*.git*" ".github*" "dist/*" "logs/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: dist/popular-search.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
