name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip Plugin
        run: |
          mkdir dist
          zip -r dist/popular-search.zip . -x "*.git*" -x "dist/*" -x ".github/*" -x "logs/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/popular-search.zip

